language: perl
perl:
  - 5.24
before_install:
  - git clone git://github.com/rjbs/travis-perl-helpers -b release-testing ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V

  - git clone git://github.com/rjbs/Ix
  - cd Ix
  - build-dist
  - perl Makefile.PL
  - make install
  - cd ..

  - cd $BUILD_DIR
script:
  - perl Makefile.PL
  - make
  - prove -b -r -s -j$(test-jobs) $(test-files)
